global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'victoria'
    static_configs:
      - targets: 
        - localhost:8428 

  - job_name: node_exporter
    static_configs:
      - targets: [node-exporter:9100]
      
  - job_name: device-api
    static_configs:
      - targets: [ act-device-api:9100 ]

