{
 "title": "Device-api",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job='device-api'},instance)"
    }
   },
   {
    "name": "http_vals",
    "query": {
     "query": "label_values(overall_quantiles,label)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU time for device-api job",
   "type": "stat",
   "description": "Uses process_cpu_seconds_total metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_cpu_seconds_total{job=\"device-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap idle bytes",
   "type": "timeseries",
   "description": "Uses go_memstats_heap_idle_bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "go_memstats_heap_idle_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "instance" },
  {
   "title": "Response time for HTTP requests (quantiles)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(overall_quantiles) by (field) / 60000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(field) (overall_meta{field=\"RPS\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time for HTTP requests by label",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(overall_quantiles) by (label) / 60000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time for all methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "avg by(field) (overall_meta)", "legendFormat": "__auto" }
   ]
  },
  { "title": "GRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Current gRPC RPS by Method",
   "type": "bargauge",
   "description": "Uses rate(grpc_server_handled_total{instance=~'$instance'}[1m]) as metric",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{instance=~'$instance'}[1m])) by (grpc_method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time by quantile",
   "type": "timeseries",
   "description": "Uses go_gc_duration_seconds metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "avg(go_gc_duration_seconds{job=\"device-api\"}) by (quantile)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC RPS by gRPC_service",
   "type": "timeseries",
   "description": "uses rate(grpc_server_handled_total{instance=~'$instance'}[1m]) as metrics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{instance=~'$instance'}[1m])) by (grpc_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handling seconds by LE",
   "type": "timeseries",
   "description": "grpc_server_handling_seconds_bucket",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handling_seconds_bucket{job=\"device-api\"})[1m]) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC average handle time by Service",
   "type": "histogram",
   "description": "Uses grpc_server_handling_seconds_bucket",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "avg(grpc_server_handling_seconds_bucket{instance=\"$instance\", job=\"device-api\"}) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}